apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nestjs-bullmq
  name: nestjs-bullmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-bullmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nestjs-bullmq
    spec:
      containers:
      - image: asmovic100/nestjs-bullmq
        name: nestjs-bullmq
        ports:
        - containerPort: 3000
        resources: {}
status: {}
